### ISSUE TITLE
Fatal Error: Sameet's repo is 2cool4me

### ISSUE THREAD

**Issue by BGR360** [sameetandpotatoes/Search-Engine#1]
What's up, skillet? You should probably fix this error, it is **very important**.

But anyway, what is this repo for? 'Tis intriguing me.

**Comment by sameetandpotatoes** [comment]
It's for an information retrieval special interest group (SIGIR) in ACM (association for computing machinery).

Yeah, it's going to be a specialized search engine for recipes, we'll see how it goes.
